### PR TITLE
Tell users when a config fails opening vs processing

### PR DESCRIPTION
**Pull request by iphands**
Configs are JS not JSON, sometimes they happen to fail and when they do Spandx says "couldn't find it, or couldn't access it". This isn't true and can confuse (I kept checking perms, path etc :D).

When a processing error occurs Spandx should tell the user, and show the error.

```
Jasmine started

  fromFile
    ✓ should load the default config (0.011 sec)
    ✓ should throw ConfigProcessError on syntax error file (0.001 sec)
    ✓ should throw ConfigOpenError on missing file (0.001 sec)

Executed 3 of 3 specs SUCCESS in 0.02 sec
```

### CODE REVIEW

**Comment by mwcz** [comment]
Pasting a patch as a comment is a very cool thing to do.

**Comment by iphands** [comment]
Totally down with that change

**Comment by iphands** [comment]
Errmmm one more remaining issue though.. precommit detects an invalid sytnax error in the file that is *supposed* to have an invalid syntax error :D

We need to shushhh that too I guess. Know how before I dig?

**Comment by iphands** [comment]
Looks like
```javascript
// prettier-ignore
```

**Comment by iphands** [comment]
Wait nvm.. its the same thing biting me still. I dont think the limit to [sS]pec.js is helping.
Is lint-staged weird... like does it use a HEAD~1 jasmine.conf until *after* the commit is validated?

I wonder if I need to just check the jasmine change in first, then come back and check in the test changes. Testing..

**Comment by iphands** [comment]
@mwcz check the changes to package.json.
The wildcard used to supply files to `prettier`, `npm test` and `git add` was causing the command line for `npm test` / jasmine to look like:
```
> jasmine spec/spandx/*.js "/tmp/spandx/spec/support/jasmine.json" "/tmp/spandx/spec/spandx/configSpec.js" "/tmp/spandx/spec/helpers/configs/invalid/syntax.js"
```

I had to modify it so that only the spec files are passed in.

**Pull request merged**
