### PR TITLE
add portal chrome injection and remove esi

### PR DESCRIPTION
**Pull request by mwcz**
It seems extremely unlikely that we're going to wind up using ESI, so I'm removing ESI from spandx and replacing it with simpler injection of Portal Chrome based on `<!-- SPA_HEAD -->`, `<!-- SPA_HEADER -->`, and `<!-- SPA_FOOTER -->` comments (same as the Drupal SPA module currently).

### CODE REVIEW

**Comment by mwcz** [comment]
@iphands Are you guys using ESI via spandx?

**Comment by mwcz** [comment]
Travis is being super slow today so I tested this with [trevor](https://github.com/vadimdemedes/trevor) instead.  Passed; merging.

**Comment by mwcz** [comment]
Merged but I won't publish official 2.0.0 until the ESI question is answered.

**Comment by iphands** [comment]
Yeah it's the primary reason for using it.
Can we leave it in as an option?

**Comment by mwcz** [comment]
@iphands I'll give it a shot.  Honestly I would have just left ESI in, but it conflicted with chrome injection via SPA comments (`<!-- SPA_HEAD -->` etc).  Instead of digging into that, I figured it would make more sense to just remove ESI, and double check that no one was using it.  So here we are!  I'll go back and try to figure out what was conflicting, might be that `transformerProxy` can't run twice on the same req/res pair.  Hmm.

**Comment by iphands** [comment]
Seems like it would make sense to have a small plug-gable arch with generic callbacks... then ESI, Portal rewrite, and something else can all be implemented and a user could choose which mode to run in. Right?

**Comment by mwcz** [comment]
For sure.  The SPA comment replacement is a config opt-in and I can do the same with ESI (once I get it working again).  Additionally, [custom middleware](https://www.browsersync.io/docs/options#option-middleware) can be registered within the `bs` block of the spandx config, but I haven't tested it.  That would allow anyone to register their own transform middleware.  So you *could* add ESI back in on your side, but I don't want to make you do that with an already-established feature.

It would still hit the conflict problem I mentioned, but I'm assuming that's just a hitch, not a dealbreaker.

**Pull request merged**
